server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-request: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&characterSetResults=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  messages:
    encoding: UTF-8

# MyBatis
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Logging
logging:
  charset:
    console: UTF-8
  level:
    cn.gdsdxy.campustrading: DEBUG